// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: 'documents',
    uri: Uri.parse('documents'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: 'epi/epi_details',
    uri: Uri.parse('epi/epi_details'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'epi/epi_list',
    uri: Uri.parse('epi/epi_list'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'epi/epi_request',
    uri: Uri.parse('epi/epi_request'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'ficha_epi',
    uri: Uri.parse('ficha_epi'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: 'home',
    uri: Uri.parse('home'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: 'login',
    uri: Uri.parse('login'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(
    key: 'notification',
    uri: Uri.parse('notification'),
    routeBuilder: b8Builder,
  ),
];

const routePaths = (
  path: '/',
  documents: '/documents',
  epi: (
    path: '/epi',
    epiDetails: '/epi/epi_details',
    epiList: '/epi/epi_list',
    epiRequest: '/epi/epi_request',
  ),
  fichaEpi: '/ficha_epi',
  home: '/home',
  login: '/login',
  notification: '/notification',
);
