// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'ui/documents/documents_page.dart' as a0;
import 'ui/epi/epi_details_page.dart' as a1;
import 'ui/epi/epi_list_page.dart' as a2;
import 'ui/epi/epi_request_page.dart' as a3;
import 'ui/ficha_epi/ficha_epi_page.dart' as a4;
import 'ui/home/home_page.dart' as a5;
import 'ui/login/login_page.dart' as a6;
import 'ui/notification/notification_page.dart' as a8;

Route b0Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a0.DocumentsPage(),
);
Route b1Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a1.EpiDetailsPage(),
);
Route b2Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a2.EpiListPage(),
);
Route b3Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a3.EpiRequestPage(),
);
Route b4Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a4.FichaEpiPage(),
);
Route b5Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a5.HomePage(),
);
Route b6Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a6.LoginPage(),
);
Route b8Builder(BuildContext ctx, RouteSettings settings) => Routefly.defaultRouteBuilder(
  ctx,
  settings,
  const a8.NotificationPage(),
);
